### ISSUE TITLE
is there any function about svd?

### ISSUE THREAD

**Issue by xichaoqiang** [MKL-NET/MKL.NET#12]
is there any function about svd like in matlab?

[[U,S,V] = svd(A)]
[[U,S,V] = svd(A,'econ')]

**Comment by AnthonyLloyd** [comment]
There isn't a simple function or test but the MKL functions to do this are exposed. Would welcome a PR for either the test or the function if you are looking to do this.

https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem/lapack-least-square-eigenvalue-problem-computation/singular-value-decomposition-lapack-computation.html#singular-value-decomposition-lapack-computation_TBL4-2
