### ISSUE TITLE
Would it be possible to add single precision Matrix/Vector types?

### ISSUE THREAD

**Issue by atlemann** [MKL-NET/MKL.NET#19]
This library looks very interesting, however, in our apps we also use a lot of single precision matrices and vectors shave off some memory usage. Would it be possible to add a single precision matrix and vector types?

**Comment by AnthonyLloyd** [comment]
I have no plans to currently (not really used in finance) but I can advice if you want to add it. I would imagine it would be very similar to the current double code.

**Comment by atlemann** [comment]
I see. I'm working in a geoscience domain where things are a bit more of a guesstimate. We use a lot of single precision to save on the memory side, since it can get a bit out of hand. I'll try to submit a PR and we could discuss the implementation there whenever you find the time.
