### ISSUE TITLE
Help calling Lapack.gesvd from C#

### ISSUE THREAD

**Issue by jdanielpa** [MKL-NET/MKL.NET#23]
I am trying to use your package to do SVD on a large matrix.  However, I am having trouble getting a simple matrix to execute.  Here is the code:

```
            int m = 3; // Number of rows
            int n = 3; // Number of columns
            double[] a = { 1, 2, 3, 4, 5, 6, 7, 8, 9 }; // Input matrix
            double[] s = new double[Math.Min(m, n)]; // Singular values
            double[] u = new double[m * m]; // Left singular vectors
            double[] vt = new double[n * n]; // Right singular vectors
            double[] superb = new double[Math.Min(m, n) - 1]; // Array for additional information

            int info = MKLNET.Lapack.gesvd( MKLNET.Layout.ColMajor, 'A', 'A', m, n, a, n, s, u, m, vt, n, superb);

```
When the code executes the gesvd line - the program crashes.  No error - just stops running. 

Any idea on what I am doing wrong?
Thanks for the help!

**Comment by AnthonyLloyd** [comment]
I'm still looking but I can't see any difference to the C example here.

https://www.intel.com/content/www/us/en/docs/onemkl/code-samples-lapack/2022-1/lapacke-dgesvd-example-c-column.html

**Comment by AnthonyLloyd** [comment]
I can't see any wrong with the code. Can you try different versions of MKL.NET.Native and also use the numbers in the example above.

**Comment by jdanielpa** [comment]
Hi Anthony.  Thanks for the response and the help!

I think I am getting closer.  I was missing the MKL.NET.win-x64 nuget package - stupid mistake.  However, now when I execute the code, it no longer crashes but the result vector and arrays are all 0.  I am using the values from the example above.  

Here is the code:

                int m = 6; // Number of rows
                int n = 5; // Number of columns
                double[] a = {  8.79,  6.11, -9.15,  9.57, -3.49,  9.84,
                                9.93,  6.91, -7.93,  1.64,  4.02,  0.15,
                                9.83,  5.04,  4.86,  8.83,  9.80, -8.99,
                                5.45, -0.27,  4.85,  0.74, 10.00, -6.02,
                                3.16,  7.98,  3.01,  5.80,  4.27, -5.31 }; // Input matrix

                double[] s = new double[Math.Min(m, n)]; // Singular values
                double[] u = new double[m * m]; // Left singular vectors
                double[] vt = new double[n * n]; // Right singular vectors
                double[] superb = new double[Math.Min(m, n) - 1]; // Array for additional information

                int info = MKLNET.Lapack.gesvd(MKLNET.Layout.ColMajor, 'A', 'A', m, n, a, n, s, u, m, vt, n, superb);

Can you test this code to confirm you get values back?  When I run the info variable = -7.  Not sure what that means but I think failure to converge means that value is > 0?

Thanks again for the help!

**Comment by jdanielpa** [comment]
Hi Anthony.  I have made some progress!  I had the wrong runtime referenced in my solution.  Using the numbers from your link above I am now getting the correct results and no crash!  I have a new problem though.  My matrix is a double[606056,36].  In the code when I hit:
`
double[] u = new double[m * m]; // Left singular vectors
`
I get an Overflow exception due to the size of m (606056).  I am not sure if there is anything I can do to handle this - thoughts?

Using another package (CenterSpace NMath) I am able execute.  I know they are using intel MKL but the signature to their method is:
```

                DoubleMatrix matrix = new DoubleMatrix(Matrix);
                var svd = new DoubleSVDecomp(matrix);
                var tmp_S = svd.SingularValues; // = double[36]
                var tmp_U = svd.LeftVectors; // = double[606056,36]
                var tmp_V = svd.RightVectors; // = double[36,36]
```

I don't have to create the large 1D array.  Is this possible with your tool?  Thanks again for the help,
Jason

**Comment by AnthonyLloyd** [comment]
I think you may need to play with jobu = 'S' and set u to be m * n.
