### ISSUE TITLE
Memory leak when using MatrixSolve with direct matrix input

### ISSUE THREAD

**Issue by tomikiss** [MKL-NET/MKL.NET#24]
We seen a constant increasing memory usage when used MatrixSolve from our code. The below example show how we used the library which  cause an extra Matrix allocated and never freed (Ea in the evaluate method as that got a copy of A which never freed).

```
int n = 400;
matrix ax = new matrix(n, n);
matrix b = new matrix(n, 1);
for (int i = 0; i < 10000; i++)
{
      MatrixSolve solve = new MatrixSolve(ax, b);
      matrix result = solve.Evaluate();
      result.Dispose();
}
ax.Dispose();
b.Dispose();
```
After this point we have 10000 extra 400*400 double array in the pool which never returned. 
Is there a better way to use this method with direct matrix input?

**Comment by AnthonyLloyd** [comment]
I can see the bug. Bug fix release coming in the next couple of days.

**Comment by AnthonyLloyd** [comment]
This has been released in MKL.NET.Matrix 1.1.1. Let me know if there is still an issue.
