### ISSUE TITLE
Cant find mkl_malloc

### ISSUE THREAD

**Issue by alloncm** [MKL-NET/MKL.NET#3]
Hi just found this awesome library and I cant find some mkl functions (especially `mkl_malloc`).
Does this library exposes all mkl functionality?
If so how does I find this function?
And if not can I access the native function and wrap in myself using this library (for the installation of mkl).

Thanks in advance.

**Comment by AnthonyLloyd** [comment]
Hi,
Yes the aim is to expose all of the MKL API in a sensible way for .NET. I've done other mkl_ functions in MKL.cs but not these as I haven't needed to use them before and don't know how to test (most other APIs like Blas etc I've exposed everything by using lots of regex to convert and then test).
If you could put in a PR adding these to MKL.cs, ideally with some kind of test for them so we know they work across OSs that would be great. Or let me know a test in C# and I'll convert to the F# testing library. The native functions will be there as we bring in the full MKL native library.
One further step towards shared awesomeness!
Thanks

**Comment by alloncm** [comment]
Thanks for the quick replay.

Next week I'll try to add some of the missing functions and if I'll succeed I'll open a new PR.
I don't really know F# so I'll try to test it with C# and I hope you could convert it to F#.

And again thanks for all the help! 😄

**Comment by AnthonyLloyd** [comment]
Timeout! Reopen if you want to continue this. Thanks
