### ISSUE TITLE
1.6.0 doesn't work in windows

### ISSUE THREAD

**Issue by minghao-guo** [MKL-NET/MKL.NET#30]
when building projects using MKL.NET 1.6.0 in windows 10, .NET 8, it throws error
`error NU1202: Package MKL.NET 1.6.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package MKL.NET 1.6.0 does not support any target frameworks.` 

It was ok with 1.5.0, and ok in linux (ubuntu 24.04) with both 1.5.0 and 1.6.0

**Comment by AnthonyLloyd** [comment]
Is this because it's win-x86? I had to remove support because the native library will no longer build.

**Comment by minghao-guo** [comment]
it is in win-x64. This is how it's used in .csproj

```
	  <PackageReference Include="MKL.NET" Version="1.6.0" /> 
	  <PackageReference Include="MKL.NET.win-x64" Version="2022.0.0.115" Condition=" '$(OS)' == 'Windows_NT' " />
	  <PackageReference Include="MKL.NET.linux-x64" Version="2022.0.1.117" Condition=" '$(OS)' == 'UNIX' " />
```

the error happened in build time

**Comment by AnthonyLloyd** [comment]
That's odd. I can't seem to reproduce added these references to a project. Can you give me a small repro. Thanks

**Comment by minghao-guo** [comment]
Tested working on a new computer. Possible some bad settings on my end. Can close this ticket.

**Comment by AnthonyLloyd** [comment]
Great, thanks
