### ISSUE TITLE
Controlling Matrix Storage

### ISSUE THREAD

**Issue by ozgurakpinar** [MKL-NET/MKL.NET#6]
Is there a way to control Matrix storage in terms of being `RowMajor `or `ColumnMajor`?

**Comment by AnthonyLloyd** [comment]
No sorry not currently. I use Column Major because I have thought in that past that was better for MKL but I've not tested it and am not sure at all of this. Is there a reason you want one over the other? I'm interested to know.

**Comment by ozgurakpinar** [comment]
Actually, if it is guaranteed that the Matrix is `always` ColumnMajor then it is also perfect. Sorry for not stating my concern better:) 

I was concerned that if I persist the array on a platform and read it on another then I would get a wrong result.

Thank you for responding. If you want you can close the issue to prevent further confusion

**Comment by AnthonyLloyd** [comment]
Ok. It's an interesting point and maybe one for the future.
