### ISSUE TITLE
Size of runtime packages

### ISSUE THREAD

**Issue by ZimmerD** [MKL-NET/MKL.NET#7]
Hi,

First of all: thank you for your work on this great library! I am currently toying around with it and so far I do really enjoy using it! 

I am currently working on some .Net CLI tools which reference the [MKL.Net](https://www.nuget.org/packages/MKL.NET/) core package as well as the [windows](https://www.nuget.org/packages/MKL.NET.win-x64/) and/or [linux](https://www.nuget.org/packages/MKL.NET.linux-x64/) runtime and I noticed that their size (runtimes) is rather large. This has the effect, that any CLI tool using the linux runtime is >250mb in size and can therefore not be hosted on nuget.org. 

Unfortunately, dependencies can not be included into cli tools by reference, but are included upon build, so the only workaround I can come up with is to shrink the size of the referenced runtimes. Do you think it would be possible to do so?

Other than that, I wondered whats the rational behind [MKL.NET.linux-x64.b](https://www.nuget.org/packages/MKL.NET.linux-x64.b/2021.4.0.640), which is referenced by the linux runtime.

Cheers

**Comment by AnthonyLloyd** [comment]
Hi,

Yes the size of these libraries is a bit of a problem. MKL.NET.linux-x64.b is a workaround for the NuGet package limit size and is referenced by MKL.NET.linux-x64.

It may be possible for you to do some pruning of the dll/so files if you know some things about what your CLI is going to do and on what type of machines.

For example if you know it will never be needed on [Xeon Phi](https://en.wikipedia.org/wiki/Xeon_Phi) then you can remove so files ending with _mic:

libmkl_avx512_mic.so.1        65,796 KB
libmkl_vml_avx512_mic.so.1 15,831 KB
etc

Also if you know you will only use the default intel threading model you can remove:

libmkl_tbb_thread.so.1    39,657 KB
libmkl_pgi_thread.so.1    37,142 KB
libmkl_gnu_thread.so.1   30,221 KB
libmkl_sequential.so.1     28,313 KB

If you know it's only going to be used on more recent arch then you could remove some of the older ones like libmkl_mc.so.1 or make the app arch specific.

If this doesn't get close enough you may need to statically compile only the function calls you actually use. This will require some C/C++. MathNet does this. I'd recommend CMake using Github actions to compile on the other platforms as I do here. You'd end up building something similar to MKL.NET on a smaller scale for it to be cross platform.

Let me know how it works out. I'm interested if it's possible to use this in a .NET CLI.

**Comment by ZimmerD** [comment]
thank you for the prompt answer!

I can already tell you that referencing the MKL.NET Core + both runtimes yielded a CLI tool (calling two lapack functions) that worked out of the box on a windows and linux test environment. I was also able to run the same code in an F# .fsx script, however this did only work out successfully using windows. 

Regarding your suggestions: I am not aware of the mkl functionality when it comes to the use of different threading models, but since I did not specify it in any way, I guess I should be able to remove those dependencies and achieve something below the magic 250mb. I will investigate this solution for runtime errors and keep you updated! Thanks again!

**Comment by ZimmerD** [comment]
Ok this was quite tricky!

So your suggestion worked just fine for my use case, I just manually deleted libmkl_tbb_thread.so.1, libmkl_pgi_thread.so.1, libmkl_gnu_thread.so.1 and libmkl_sequential.so.1 and the application kept running fine and produced the correct results, both on linux and on windows using dotnet run.

However, doing the deletes in the build process, package the application as a tool, install it as a tool and running the installed tool was not as trivial. The main reason for this is that nuget packages are not thought to be modified by the referencing application and their completeness - according to how it was initially packed - is checked, during the built, the packaging and even when you call the tool. So if you modify the runtimes using and post build event: they will be restored using dotnet pack - even if you call it with the option --no-build. If you delete them from the nuget package - the tool will not run since it is always checked if all files of all referenced nuget packages are complete before running the tool. 

Long story short: I was able to make it work by adding the following lines to my .fsproj file:

First of all I set the reference to the linux runtime to private using:

```
    <PackageReference Include="MKL.NET.linux-x64" Version="2021.4.0.640" >
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

This will have the effect that the reference to the runtime is not included and thus dotnet pack will not restore the DLLs 
which I delete using: 

```
  <Target Name="Delete_libmkl_tbb_thread" AfterTargets="Build">
      <Message Text="Deleting $(OutDir)/runtimes/linux-x64/native/libmkl_tbb_thread.so.1"/>
      <Delete Files="$(OutDir)/runtimes/linux-x64/native/libmkl_tbb_thread.so.1" />
  </Target>
  <Target Name="Delete_libmkl_pgi_thread" AfterTargets="Build">
      <Message Text="Deleting $(OutDir)/runtimes/linux-x64/native/libmkl_pgi_thread.so.1"/>
      <Delete Files="$(OutDir)/runtimes/linux-x64/native/libmkl_pgi_thread.so.1" />
  </Target>
  <Target Name="Delete_libmkl_gnu_thread" AfterTargets="Build">
      <Message Text="Deleting $(OutDir)/runtimes/linux-x64/native/libmkl_gnu_thread.so.1"/>
      <Delete Files="$(OutDir)/runtimes/linux-x64/native/libmkl_gnu_thread.so.1" />
  </Target>
  <Target Name="Delete_libmkl_sequential" AfterTargets="Build">
      <Message Text="Deleting $(OutDir)/runtimes/linux-x64/native/libmkl_sequential.so.1"/>
      <Delete Files="$(OutDir)/runtimes/linux-x64/native/libmkl_sequential.so.1" />
  </Target>
```

However, since now this is not tracked I have to specify which runtimes to copy and how to pack them which I did by adding:
```

  <ItemGroup>
      <Content Include="bin/Release/$(TargetFramework)/runtimes/linux-x64/native/*.so" Exclude="bin/Release/$(TargetFramework)/runtimes/linux-x64/native/MKL.NET.Native.so">
        <Pack>true</Pack>
        <PackagePath>\tools\$(TargetFramework)\any\</PackagePath>
      </Content>
      <Content Include="bin/Release/$(TargetFramework)/runtimes/linux-x64/native/*.so.1" >
        <Pack>true</Pack>
        <PackagePath>\tools\$(TargetFramework)\any\</PackagePath>
      </Content>
  </ItemGroup>

```

The only problem left now, is that on tool execution - even so I used  `<PrivateAssets>all</PrivateAssets> ` - the toolname.deps.json file is used to check if the nuget packages are complete - which they are not - and the execution is stopped.

To circumvent this, I added 

`<GenerateDependencyFile>false</GenerateDependencyFile>`

Now the only problem left is, that during runtime, the tool can not localize the MKL.NET.dll, since it is not packed in the project root, but in the lib folder next to the runtimes. Thus you have to add: 

```

  <ItemGroup>
      <Content Include="bin/Release/$(TargetFramework)/runtimes/linux-x64/lib/netstandard2.0/MKL.NET.dll">
        <Pack>true</Pack>
        <PackagePath>\tools\$(TargetFramework)\any\</PackagePath>
      </Content>
  </ItemGroup>
```

So it is located during execution. It was also necessary to move the runtimes to the project root, which I also did via:
`<PackagePath>\tools\$(TargetFramework)\any\</PackagePath>` (see the XML following: However, since now this is not tracked I have to specify w...)

Following these steps I now managed to create a dotnet cli tool for linux which is sub 250 MB in size and installs and runs as any other tool would.

**Comment by AnthonyLloyd** [comment]
Wow. And this comes from .NET CLI not supporting package dependencies and having the NuGet size limit. I hope one of these changes.

**Comment by ZimmerD** [comment]
Sadly, the .NET CLI supporting package dependencies does not seem like something on the road map (at least this is what I deduced from [here](https://github.com/dotnet/sdk/issues/10875)). 

One could think about to extend the approach you are now using to get the linux runtime packages up (split in main and .b) one step further and divide them into more packages, according to function. This would allow package consumers to refer only to runtime components they will be using, e.g only lapack, or only blas and so on. This could save people from going the extra mile to generate a stripped down copy from MKL.NET and thus lead to broader adoption of the package. 

Since a solution for this issue is now found, we can close the issue, as far as I am concerned! Thank you for you help!

**Comment by AnthonyLloyd** [comment]
No problem. I'll have a think about creating slim versions and what that should be.
