### ISSUE TITLE
Intel's IPP library

### ISSUE THREAD

**Issue by ghost** [MKL-NET/MKL.NET#9]
Just an idea, since you already have a build pipeline in place for packaging cross-platform libraries (and maybe for generating the P/Invoke boilerplate, although maybe that is handcrafted?)

We've had good experiences with Intel's other library IPP (Integrated Performance Primitives), it offers some functionality that MKL lacks like vector-scalar binary operations (e.g. add constant to vector), threshold operations and more.

It might be out of scope for this project, just tell me what you think. I might be able to contribute some P/Invoke definitions if you're interested, subject to my employer's permission.

**Comment by AnthonyLloyd** [comment]
The P/Invokes were build from the .h files and a lot of regex search and replace.

I'll take a look at IPP, I've never used it. It would effectively be completely parallel I would presume with it's own native dlls.

**Comment by AnthonyLloyd** [comment]
I've had a look and I think the whole implementation would be a separate repo. It would be very similar in structure but I don't think anything would be shared.

The tests would also need to be written by someone with an interest these areas.

So unless there's anything I'm missing I think it should be a sister repo and packages if someone was interested in doing that. We could obviously share techniques and ideas.

**Comment by ghost** [comment]
No problem, closing it. I will need to check whether I can create such a project in the future.
